/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSegmentArgs } from "./CreateSegmentArgs";
import { UpdateSegmentArgs } from "./UpdateSegmentArgs";
import { DeleteSegmentArgs } from "./DeleteSegmentArgs";
import { SegmentFindManyArgs } from "./SegmentFindManyArgs";
import { SegmentFindUniqueArgs } from "./SegmentFindUniqueArgs";
import { Segment } from "./Segment";
import { Annotation } from "../../annotation/base/Annotation";
import { Title } from "../../title/base/Title";
import { SegmentService } from "../segment.service";

@graphql.Resolver(() => Segment)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SegmentResolverBase {
  constructor(
    protected readonly service: SegmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "read",
    possession: "any",
  })
  async _segmentsMeta(
    @graphql.Args() args: SegmentFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Segment])
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "read",
    possession: "any",
  })
  async segments(
    @graphql.Args() args: SegmentFindManyArgs
  ): Promise<Segment[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Segment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "read",
    possession: "own",
  })
  async segment(
    @graphql.Args() args: SegmentFindUniqueArgs
  ): Promise<Segment | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Segment)
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "create",
    possession: "any",
  })
  async createSegment(
    @graphql.Args() args: CreateSegmentArgs
  ): Promise<Segment> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        annotation: args.data.annotation
          ? {
              connect: args.data.annotation,
            }
          : undefined,

        title: args.data.title
          ? {
              connect: args.data.title,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Segment)
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "update",
    possession: "any",
  })
  async updateSegment(
    @graphql.Args() args: UpdateSegmentArgs
  ): Promise<Segment | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          annotation: args.data.annotation
            ? {
                connect: args.data.annotation,
              }
            : undefined,

          title: args.data.title
            ? {
                connect: args.data.title,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Segment)
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "delete",
    possession: "any",
  })
  async deleteSegment(
    @graphql.Args() args: DeleteSegmentArgs
  ): Promise<Segment | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Annotation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "read",
    possession: "any",
  })
  async annotation(
    @graphql.Parent() parent: Segment
  ): Promise<Annotation | null> {
    const result = await this.service.getAnnotation(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Title, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Title",
    action: "read",
    possession: "any",
  })
  async title(@graphql.Parent() parent: Segment): Promise<Title | null> {
    const result = await this.service.getTitle(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
