/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SegmentService } from "../segment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SegmentCreateInput } from "./SegmentCreateInput";
import { SegmentWhereInput } from "./SegmentWhereInput";
import { SegmentWhereUniqueInput } from "./SegmentWhereUniqueInput";
import { SegmentFindManyArgs } from "./SegmentFindManyArgs";
import { SegmentUpdateInput } from "./SegmentUpdateInput";
import { Segment } from "./Segment";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SegmentControllerBase {
  constructor(
    protected readonly service: SegmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Segment })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: SegmentCreateInput): Promise<Segment> {
    return await this.service.create({
      data: {
        ...data,

        annotation: data.annotation
          ? {
              connect: data.annotation,
            }
          : undefined,

        title: data.title
          ? {
              connect: data.title,
            }
          : undefined,
      },
      select: {
        annotation: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        duration: true,
        endSample: true,
        fileAbsolutePath: true,
        filename: true,
        id: true,
        startSample: true,

        title: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Segment] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(SegmentFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Segment[]> {
    const args = plainToClass(SegmentFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        annotation: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        duration: true,
        endSample: true,
        fileAbsolutePath: true,
        filename: true,
        id: true,
        startSample: true,

        title: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Segment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: SegmentWhereUniqueInput
  ): Promise<Segment | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        annotation: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        duration: true,
        endSample: true,
        fileAbsolutePath: true,
        filename: true,
        id: true,
        startSample: true,

        title: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Segment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: SegmentWhereUniqueInput,
    @common.Body() data: SegmentUpdateInput
  ): Promise<Segment | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          annotation: data.annotation
            ? {
                connect: data.annotation,
              }
            : undefined,

          title: data.title
            ? {
                connect: data.title,
              }
            : undefined,
        },
        select: {
          annotation: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          duration: true,
          endSample: true,
          fileAbsolutePath: true,
          filename: true,
          id: true,
          startSample: true,

          title: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Segment",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Segment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: SegmentWhereUniqueInput
  ): Promise<Segment | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          annotation: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          duration: true,
          endSample: true,
          fileAbsolutePath: true,
          filename: true,
          id: true,
          startSample: true,

          title: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
