/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AnnotationService } from "../annotation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnnotationCreateInput } from "./AnnotationCreateInput";
import { AnnotationWhereInput } from "./AnnotationWhereInput";
import { AnnotationWhereUniqueInput } from "./AnnotationWhereUniqueInput";
import { AnnotationFindManyArgs } from "./AnnotationFindManyArgs";
import { AnnotationUpdateInput } from "./AnnotationUpdateInput";
import { Annotation } from "./Annotation";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AnnotationControllerBase {
  constructor(
    protected readonly service: AnnotationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Annotation })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: AnnotationCreateInput
  ): Promise<Annotation> {
    return await this.service.create({
      data: {
        ...data,

        segment: data.segment
          ? {
              connect: data.segment,
            }
          : undefined,
      },
      select: {
        annotation: true,
        cleansedAnnotation: true,
        createdAt: true,
        emotionalType: true,
        id: true,
        isValid: true,

        segment: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Annotation] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(AnnotationFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Annotation[]> {
    const args = plainToClass(AnnotationFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        annotation: true,
        cleansedAnnotation: true,
        createdAt: true,
        emotionalType: true,
        id: true,
        isValid: true,

        segment: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: AnnotationWhereUniqueInput
  ): Promise<Annotation | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        annotation: true,
        cleansedAnnotation: true,
        createdAt: true,
        emotionalType: true,
        id: true,
        isValid: true,

        segment: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() data: AnnotationUpdateInput
  ): Promise<Annotation | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          segment: data.segment
            ? {
                connect: data.segment,
              }
            : undefined,
        },
        select: {
          annotation: true,
          cleansedAnnotation: true,
          createdAt: true,
          emotionalType: true,
          id: true,
          isValid: true,

          segment: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: AnnotationWhereUniqueInput
  ): Promise<Annotation | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          annotation: true,
          cleansedAnnotation: true,
          createdAt: true,
          emotionalType: true,
          id: true,
          isValid: true,

          segment: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
